<?php
/**
 * web/public/login.php — Login page for mailbox review app.
 *
 * Two roles available:
 *   coworker — can review and update decisions; display name is mandatory.
 *   admin    — can import, export, and view all decisions.
 *
 * POST parameters:
 *   role         : 'coworker' | 'admin'
 *   password     : plaintext password (verified against hash in config)
 *   display_name : required for coworker role; optional for admin
 *   csrf_token   : CSRF token (generated on GET and embedded in form)
 *
 * Security:
 *   - Password is verified with password_verify() against bcrypt hash from config.
 *   - session_regenerate_id(true) called on successful login (via SessionManager).
 *   - CSRF token validated on POST to prevent login CSRF.
 *   - No information about which credential is wrong (generic error only).
 */

declare(strict_types=1);

// ── Config bootstrap ──────────────────────────────────────────────────────────
ini_set('display_errors', '0');
ini_set('log_errors', '1');
error_reporting(E_ALL);

set_exception_handler(function (Throwable $e): void {
    http_response_code(500);
    echo 'Internal server error. Please contact the administrator.';
    error_log('Login exception: ' . $e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine());
    exit(1);
});

set_error_handler(function (int $errno, string $errstr, string $errfile, int $errline): bool {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
});

$configPath = dirname(__DIR__) . '/config/local.php';
if (!is_file($configPath)) {
    http_response_code(500);
    echo 'Service unavailable: configuration missing.';
    error_log('Missing config file: ' . $configPath);
    exit(1);
}

/** @var array<string,mixed> $config */
$config = require $configPath;

// ── Autoload ──────────────────────────────────────────────────────────────────
spl_autoload_register(function (string $class): void {
    $prefix  = 'MailReview\\';
    $baseDir = dirname(__DIR__) . '/src/';
    if (!str_starts_with($class, $prefix)) {
        return;
    }
    $relative = substr($class, strlen($prefix));
    $file     = $baseDir . str_replace('\\', '/', $relative) . '.php';
    if (is_file($file)) {
        require $file;
    }
});

// ── Security headers ──────────────────────────────────────────────────────────
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');
header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'");

// ── Session + CSRF bootstrap ──────────────────────────────────────────────────
$session = new \MailReview\Auth\SessionManager($config['session'] ?? []);
$session->start();

// Redirect to dashboard if already logged in
if ($session->isAuthenticated()) {
    header('Location: /', true, 302);
    exit(0);
}

$csrf        = new \MailReview\Auth\CsrfGuard();
$errorMsg    = '';
$formRole    = 'coworker';
$formDisplay = '';

// ── Handle POST login ─────────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // 1. CSRF check first
    if (!$csrf->validateToken($_POST['csrf_token'] ?? '')) {
        http_response_code(403);
        echo 'CSRF validation failed.';
        exit(0);
    }

    $role        = trim($_POST['role'] ?? '');
    $password    = (string)($_POST['password'] ?? '');
    $displayName = trim($_POST['display_name'] ?? '');

    if (!in_array($role, ['coworker', 'admin'], true)) {
        $errorMsg = 'Invalid role selected.';
    } elseif ($role === 'coworker' && $displayName === '') {
        $errorMsg = 'Display name is required for coworker login.';
        $formRole = 'coworker';
    } else {
        $formRole    = $role;
        $formDisplay = $displayName;

        // Get the appropriate hash from config
        $hash = ($role === 'admin')
            ? (string)($config['admin_password_hash']    ?? '')
            : (string)($config['coworker_password_hash'] ?? '');

        if ($session->login($role, $password, $hash, $displayName)) {
            // Successful login — redirect to dashboard
            // Regenerate CSRF token after login (session was regenerated by SessionManager)
            $csrf->generateToken();
            header('Location: /', true, 302);
            exit(0);
        } else {
            // Generic error — do not reveal which credential was wrong
            $errorMsg = 'Invalid credentials. Please try again.';
        }
    }
}

// ── Render login form ─────────────────────────────────────────────────────────
$csrfToken = htmlspecialchars($csrf->getToken(), ENT_QUOTES, 'UTF-8');
$errorHtml = $errorMsg !== ''
    ? '<div class="error">' . htmlspecialchars($errorMsg, ENT_QUOTES, 'UTF-8') . '</div>'
    : '';
$roleCoworkerSelected = ($formRole === 'coworker') ? ' selected' : '';
$roleAdminSelected    = ($formRole === 'admin')    ? ' selected' : '';
$displayNameValue     = htmlspecialchars($formDisplay, ENT_QUOTES, 'UTF-8');

?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login — Mailbox Review</title>
    <style>
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: system-ui, -apple-system, sans-serif;
            background: #f5f5f5;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            color: #222;
        }
        .login-card {
            background: #fff;
            border: 1px solid #ddd;
            border-radius: 6px;
            padding: 2rem 2.5rem;
            width: 100%;
            max-width: 400px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.06);
        }
        h1 {
            font-size: 1.4rem;
            font-weight: 600;
            margin-bottom: 1.5rem;
            color: #111;
        }
        label {
            display: block;
            font-size: 0.875rem;
            font-weight: 500;
            margin-bottom: 0.3rem;
            color: #444;
        }
        input, select {
            display: block;
            width: 100%;
            padding: 0.5rem 0.75rem;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 1rem;
            margin-bottom: 1rem;
            background: #fff;
            color: #222;
        }
        input:focus, select:focus {
            outline: 2px solid #0066cc;
            outline-offset: 1px;
            border-color: #0066cc;
        }
        button[type="submit"] {
            width: 100%;
            padding: 0.6rem 1rem;
            background: #0066cc;
            color: #fff;
            border: none;
            border-radius: 4px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
        }
        button[type="submit"]:hover { background: #0055aa; }
        .error {
            background: #fff0f0;
            border: 1px solid #fcc;
            color: #c00;
            border-radius: 4px;
            padding: 0.5rem 0.75rem;
            margin-bottom: 1rem;
            font-size: 0.9rem;
        }
        .display-name-row { transition: opacity 0.15s; }
        .display-name-row.hidden { display: none; }
    </style>
</head>
<body>
<div class="login-card">
    <h1>Mailbox Review — Login</h1>
    <?= $errorHtml ?>
    <form method="post" action="/login.php" autocomplete="off">
        <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">

        <label for="role">Role</label>
        <select id="role" name="role" onchange="updateForm(this.value)">
            <option value="coworker"<?= $roleCoworkerSelected ?>>Coworker (reviewer)</option>
            <option value="admin"<?= $roleAdminSelected ?>>Admin</option>
        </select>

        <div class="display-name-row" id="displayNameRow">
            <label for="display_name">Your display name <span style="color:#c00">*</span></label>
            <input
                type="text"
                id="display_name"
                name="display_name"
                value="<?= $displayNameValue ?>"
                placeholder="e.g. Anna M."
                maxlength="80"
                autocomplete="nickname"
            >
        </div>

        <label for="password">Password</label>
        <input
            type="password"
            id="password"
            name="password"
            autocomplete="current-password"
            required
        >

        <button type="submit">Log in</button>
    </form>
</div>
<script>
function updateForm(role) {
    var row = document.getElementById('displayNameRow');
    var inp = document.getElementById('display_name');
    if (role === 'admin') {
        row.classList.add('hidden');
        inp.removeAttribute('required');
    } else {
        row.classList.remove('hidden');
        inp.setAttribute('required', '');
    }
}
// Set initial state
updateForm(document.getElementById('role').value);
</script>
</body>
</html>
